name: 'Organize Project Cards with Columns Icons'
description: 'The name of columns need use a icon separate by hifen, like "😀 - Column Name", them all card will be title with icon "😀 Name of Card".
When a card change of column, the icon will be updated from this column.'
author: 'Fabiano Chiaretto Fernandes'
branding:
  icon: 'edit'
  color: 'purple'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true