name: Update Cards Project

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  update-cards:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Update Card Project
        uses: chiaretto/github-action-organize-cards-columns-project@master
        with:
          github-token: "${{ secrets.ACCESS_TOKEN }}"