name: Update Columns Project

on:
  workflow_dispatch:
    inputs:
      debug:
        type: choice
        options:
          - true
          - false

jobs:
  update-cards:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Update Card Project
        uses: chiaretto/github-action-organize-cards-columns-project@master
        with:
          github-token: "${{ secrets.ACCESS_TOKEN }}"
          debug: "${{ github.event.inputs.debug }}"